### ISSUE TITLE
iOS Version

### ISSUE THREAD

**Issue by treed593** [exteso/Alf.ioBackoffice#8]
Is an iOS version on the roadmap?

**Comment by cbellone** [comment]
not yet, we're evaluating different options before planning it. Any help would be highly appreciated

**Comment by treed593** [comment]
I would be glad to help in any way possible.

**Comment by cbellone** [comment]
Hi @treed593,
FYI we have just got the approval for a public beta on the apple store. We are very close to release our iOS version :-)

Are you still interested in helping us? 

Thanks,
Celestino
